# Experiment parameters
phase: "test"     # "train", "test"
device: "cpu"

# Data path
data_dir: "data"

# Pre-saved model path and name
saved_models_dir: "saved_models"
model_name: "model_1694345338.hdf5"

# Model training parameters
input_shape: [224, 224]
validation_split: 0.3
test_split: 0.3
batch_size: 64
learning_rate: 0.001
epochs: 20

white_labels: ['Digital art', 'NFT art', 'Photography', 'Illustration', 'Painting', 'Abstract art', 'Conceptual art',
               'Drawing', '3D art', 'Animation', 'Collage', 'Graphic design', 'Nude art', 'Video art', 'Curator',
               'Poetry', 'Writing', 'Pop art', 'Installation art', 'Architecture', 'Filmmaking', 'Music composition',
               'Street art', 'Fashion', 'Motion design', 'Anime', 'Calligraphy', 'Modelling', 'Music production',
               'Body art', 'Sculpture']
